
backend:
  name: github
  repo: alberto56/suresh-issue-123
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/68a4843ea01ae4d50752b8a9
media_folder: 'docs/media'
public_folder: "/media"
collections:
  - name: 'blog'
    create: true
    label: 'Articles'
    folder: 'docs/jekyll_blogposts/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
